### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by Jorropo** [berty/www.berty.tech#142]
While trying to fix #4 I'm not able to build (`berty{tech,art}/`) :
```
$USER@$HOSTNAME:~/Documents/Scripts/www.berty.tech/bertytech$ ./pre-build.sh 
$USER@$HOSTNAME:~/Documents/Scripts/www.berty.tech/bertytech$ make dev
hugo server -D -F --disableFastRender --bind=0.0.0.0 --baseURL=/ --appendPort=false
Building sites … ERROR 2020/09/03 23:36:36 failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:2:3: executing "_default/single.html" at <partial "head" .>: error calling partial: "/home/$USER/Documents/Scripts/www.berty.tech/bertytech/layouts/partials/head.html:98:38": execute of template failed: template: partials/head.html:98:38: executing "partials/head.html" at <$style.Content>: error calling Content: TOCSS: failed to transform "bundle.scss" (text/x-scss): resource "scss/bundle.scss_66c51675248977a80b16bae70957083e" not found in file cache
Built in 930 ms
Error: Error building site: TOCSS: failed to transform "bundle.scss" (text/x-scss): resource "scss/bundle.scss_66c51675248977a80b16bae70957083e" not found in file cache
make: *** [Makefile:8: dev] Error 255
$USER@$HOSTNAME:~/Documents/Scripts/www.berty.tech/bertytech$ hugo version
Hugo Static Site Generator v0.74.3-DA0437B4 linux/amd64 BuildDate: 2020-07-23T16:22:34Z
```
It seems like netlify is grabing the file from his cache instead of building it.
Did I miss something in the build process ?

**Comment by cdeleeuwe** [comment]
Hi @Jorropo, thanks a lot for contributing. 

Usually this error occurs when either not using the Hugo EXTENDED version or when the node modules weren't installed.

From what I see from your snippet, is I think you are using the regular Hugo version (not Extended). The ```hugo version``` output should be ```Hugo Static Site Generator v0.74.3-DA0437B4/extended```.

Can you please check if you both have the Hugo extended version installed and did an ```npm install``` before the build?

**Comment by Jorropo** [comment]
> Hi @Jorropo, thanks a lot for contributing.
> 
> Usually this error occurs when either not using the Hugo EXTENDED version or when the node modules weren't installed.
> 
> From what I see from your snippet, is I think you are using the regular Hugo version (not Extended). The `hugo version` output should be `Hugo Static Site Generator v0.74.3-DA0437B4/extended`.
> 
> Can you please check if you both have the Hugo extended version installed and did an `npm install` before the build?

thx, works fine with extended version :)
