### ISSUE TITLE
Fix amp-script obs-email sometimes not triggered

### ISSUE THREAD

**Issue by cdeleeuwe** [berty/www.berty.tech#152]
Sometimes the amp-script isn't triggered and the obfuscated email address isn't showing. For example on the FAQ page sometimes it shows as.. 

![image](https://user-images.githubusercontent.com/11793788/92474929-cd851d00-f206-11ea-813c-46bc1f22e3a6.png)

**Comment by jefft0** [comment]
Related to https://github.com/berty/www.berty.tech/issues/315

**Comment by iuricmp** [comment]
The website doesn't contain this button anymore. Should we close this ticket?

<img width="800" alt="Screenshot 2024-02-23 at 17 22 22" src="https://github.com/berty/www.berty.tech/assets/689440/2ac03fa7-7dde-4380-ba1e-30c6375e186c">

**Comment by jefft0** [comment]
This button is not on the web site anymore. Close.
