### ISSUE TITLE
reading time issue

### ISSUE THREAD

**Issue by pierreboc** [berty/www.berty.tech#203]
![image](https://user-images.githubusercontent.com/31745588/100206711-fdd78000-2f06-11eb-9dd0-8e4d85479769.png)

It happens when the author contains the first + last name. 

@cdeleeuwe can you handle this? 

Thx :-)

**Comment by cdeleeuwe** [comment]
@pierreboc It's because it doesn't have enough space to put it on a single line. We could either make it 2 lines, or maybe a better option would be to make "minutes de lecture" shorter. Is it possible to use shorter words in French for this?

**Comment by pierreboc** [comment]
@cdeleeuwe "minutes" can be shorter -> "min"
