### ISSUE TITLE
Very large shields (badges) on the docs page

### ISSUE THREAD

**Issue by LFGaming** [berty/www.berty.tech#271]
In the [docs/berty](https://berty.tech/docs/berty/) site the shields are very big, taking up almost the entire screen.

![image](https://user-images.githubusercontent.com/38732192/119681819-afb62180-be42-11eb-9ca1-cf1b6a3eaa6c.png)

**Comment by mawoka-myblock** [comment]
The link is wrong, it links to this issue, but you are right!

**Comment by LFGaming** [comment]
> The link is wrong, it links to this issue, but you are right!

Thanks, I've changed the link now :), I also send a pull request where i fixed it, but it has not yet been reviewed :)

**Comment by aeddi** [comment]
Thanks for your contribution @LFGaming ;)
