### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by moul** [berty/www.berty.tech#3]
Configure the website to support i18n
* [x] Configure Hugo
* [ ] Update .RelPermalink to RelLangPermalink
* [x] Add alternate lang meta tags
* [x] Add crowdin config
* [ ] Shortcodes
* [ ] Authors
* [ ] Dates
* [ ] Partials
* [ ] Footer
* [ ] Menu items
* [x] About Page
* [x] Blog Page (list & single)
* [x] Challenges Page
* [x] Apps compare table
* [ ] Contact Page
* [ ] Contribute Page
* [x] Docs Page (list & single)
* [ ] Download Page
* [ ] FAQ Page
* [ ] Features Page
* [ ] Help Page
* [ ] Jobs Page (list & single)
* [x] Newsletter Page (list & single)
* [x] Press Page
* [x] Privacy Policy Page
* [x] Terms Page
* [ ] Home Page
* [ ] Easteregg Page
* [ ] Hello Page
* [ ] Id Page
* [ ] Fix relative assets paths with language prefix

---

* [ ] Connect crowdin.com
* [ ] initial french translation for the interface
* [ ] translate one of the blogposts

**Comment by moul** [comment]
Related with https://github.com/berty/berty/issues/1820

Maybe we can try to find a unique translation system for all the projects?

**Comment by pierreboc** [comment]
We now have Crowdin for our translation.

-> https://translate.berty.community/
