### ISSUE TITLE
Please bring back the newsletter

### ISSUE THREAD

**Issue by sudwhiwdh** [berty/www.berty.tech#350]
I am curious to learn more about what is currently happening in Berty's ecosystem.

**Comment by LFGaming** [comment]
The team is very bussy, but they are starting tings back up to let the community know whats happening. Now we get (about) weekly updates in the discord about whats happend last week, if you have not yet joined the discord feel free to come and say hi: https://crpt.fyi/berty-discord

**Comment by sudwhiwdh** [comment]
I am glad to read that there are regular news.
Unfortunately, this is not conceivable for me via Discord.
https://github.com/berty/berty/discussions/4567#discussion-4809190
And I am happy if there is also an alternative way, like the blog, to share about it.

**Comment by LFGaming** [comment]
I just heard from the team that the newsletters will be resumed shortly

**Comment by sudwhiwdh** [comment]
Thanks for your update!
Especially in view of a release, I would find an updating roadmap exciting.
Either on GitHub or here is an example of Cwtch in documentation form
https://docs.cwtch.im/blog/cwtch-stable-roadmap-update/

**Comment by sudwhiwdh** [comment]
What exactly did you want to link to? The link does not work.

**Comment by LFGaming** [comment]
oh sorry, thought the link worked,, i linked to [www.wesh.network](https://wesh.network/)
also I know that the team wants to be more transparent (show better what is being done when) and a roadmap that comes along with it, I am not sure when that will be done, since it ofcourse takes time to fix such things but they are going to make such things 👍

**Comment by jefft0** [comment]
Hello @sudwhiwdh . Is this issue resolved? Can it be closed?

**Comment by sudwhiwdh** [comment]
@jefft0 Thank you for your question!
As soon as there is a newsletter again or a similar publicly accessible page, the issue will be solved for me.
So far, the last newsletter is still from 2 February 22.

**Comment by sudwhiwdh** [comment]
Maybe you can remove the question label? For me, it's more of a feature request.

**Comment by LFGaming** [comment]
Hi @sudwhiwdh I am happy to announce that the newsletters will start again. The first one should be out in about two weeks, so expect one soon!

**Comment by sudwhiwdh** [comment]
The latest newsletter cannot be found at https://berty.tech/newsletter.

**Comment by sudwhiwdh** [comment]
@LFGaming What does it take to publish the latest newsletter https://github.com/berty/www.berty.tech/pull/397?

**Comment by LFGaming** [comment]
> @LFGaming What does it take to publish the latest newsletter #397?

Hi sorry for the delay, the team has been very busy. I just talked with @costinberty he will focus on it starting friday, it will max take two weeks. A lot has happened and changed so this first takes longer than expected I hope you can understand.

Greetings LF

**Comment by LFGaming** [comment]
Hi @sudwhiwdh It took a while, but finaly the newsletters have started again, I hope you will like it.
[newest newsletter](https://berty.tech/newsletter/news-72/)
