### ISSUE TITLE
[BUG] small letters at the starting keys section get cut off

### ISSUE THREAD

**Issue by LFGaming** [berty/www.berty.tech#363]
The small letters at the [starting keys](https://berty.tech/docs/protocol/#starting-keys) get cut off. When not zoomed in its hard to see what letter it is. (not only this section, but this is an example).
See Image:
![image](https://user-images.githubusercontent.com/38732192/230486063-d38c9938-308b-4aa1-88e8-e2c418a89fbc.png)

**Comment by jefft0** [comment]
@LFGaming , is this still an issue? It looks OK for me on desktop and mobile (Firefox, Chrome). I can zoom this section OK.

**Comment by LFGaming** [comment]
Hi @jefft0, It indeed seems fixed now, ill close this issue
