### ISSUE TITLE
[Bug]'s in the quick acces FAQ menu at the bottom right.

### ISSUE THREAD

**Issue by LFGaming** [berty/www.berty.tech#367]
1. Link on the FAQ section of the quick awnsers menu at the bottom right is broken to github good first issues.

In the bottom right in that quick answers menu, under the FAQ section, How can I contribute?. There is a link to the [Good first issue](https://github.com/berty/berty/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) label in the github issues, but you see the entire link.

See image:
![brave_2023-04-14_15-01-10](https://user-images.githubusercontent.com/38732192/232099449-34bb5cac-5900-4dd9-88ba-f78b6675a535.png)

https://user-images.githubusercontent.com/38732192/232099974-ec12c41f-8fd5-46e1-95c1-238b39276961.mp4

</br></br>

2. Can I trust berty in the FaQ help menu clips out of the box.
The "Can I trust berty" section in the FaQ help menu in the bottom right corner clips out of the box so you cant read the text.

See image:
![brave_2023-04-06_22-13-30](https://user-images.githubusercontent.com/38732192/232099681-cb2f307d-842a-48c8-8e06-115ed28692ef.png)
Tested on the following devices:
Desktop: Brave browser, Google Chrome, Firefox and Microsoft Edge.
Phone (Iphone 12 mini, Ios 16.4.1): Safari, Brave browser and Google.
Phone (Samsung galaxy S20 5G, Android 13): Samsung Internet, Google Chrome.
All have this issue.

https://user-images.githubusercontent.com/38732192/232099944-3c48592a-945f-4646-a83d-bb672c13d2f5.mp4

</br></br>

3. Feature request still links to vote.berty.community , but that site has been closed.
![brave_2023-04-14_17-58-57](https://user-images.githubusercontent.com/38732192/232100334-509c01f9-1f39-4527-a2df-61968bbfa204.png)

https://user-images.githubusercontent.com/38732192/232100475-c3b4f971-5a72-49a1-92d0-fc6913d43e31.mp4

</br></br>

4. The Adding a Contact page has a lot of empty room around the headings, while the other pages don't have this much space between them.

Adding a Contact page:
![brave_2023-04-14_17-57-38](https://user-images.githubusercontent.com/38732192/232100680-c36df989-dd60-4ac6-976f-8fb667ee0cf2.png)

Example of any other:
![brave_2023-04-14_17-57-49](https://user-images.githubusercontent.com/38732192/232100770-60c46cfe-6741-468b-a3af-cf00b5eb3a40.png)

https://user-images.githubusercontent.com/38732192/232101014-a5acecba-9b2d-4c2a-b97e-80d2f0fc872c.mp4

</br></br>

@iuricmp asked me to put the problems in one issue, that why this one has multible problems in one 👍

**Comment by jefft0** [comment]
We reviewed and confirmed. @iuricmp will take a look at the low-hanging fruit.

**Comment by jefft0** [comment]
Hi @LFGaming . There have been many changes to the web site since opening this issue. Can you please confirm if some or all of these are still an issue?

**Comment by LFGaming** [comment]
Hi @jefft0 , the entire FAQ menu at the bottom has been removed so this issue is fixed 👍
