### ISSUE TITLE
[BUG] Pressable download button goes way further than the picture.

### ISSUE THREAD

**Issue by LFGaming** [berty/www.berty.tech#368]
Hi, the pressable space for the download on android and iphone goes way beyond the picture. This is for both the android and ios pictures.

In the image you can see how far it goes (I don't know if that is the right thing i selected, but it goes just as far as the pressable space):
![image](https://user-images.githubusercontent.com/38732192/232236759-811f25a7-06d3-4c75-ab51-a764e52dceec.png)

**Comment by jefft0** [comment]
Hi @LFGaming . Is this still an issue on the updated web site? (I can't find this page.)

**Comment by LFGaming** [comment]
> Hi @LFGaming . Is this still an issue on the updated web site? (I can't find this page.)

Hi @jefft0, It was at the home page (first thing below the now `Unstoppable P2P Communication` text) but they buttons are indeed gone so no issue anymore 👍
