### ISSUE TITLE
[BUG] Issues with Projects we love button.

### ISSUE THREAD

**Issue by LFGaming** [berty/www.berty.tech#370]
### For the Brave Browser:
The `Projects we love` button under the `Developers` dropdown only sends you to the right part when you are already on the `Contribute` page. When on another part of the site you get send to the `Contribute` page.

See video of the brave browser:
https://user-images.githubusercontent.com/38732192/232624656-2ac2c15c-6c35-4b8e-b214-f8978fa47063.mp4

### For firefox:
Depending on your screen resolution, you sometimes get send to the bottom of the page.

See video of a 2k resolution in firefox (It goes to the bottom of the screen):
https://user-images.githubusercontent.com/38732192/232625455-ffb5be8a-3a79-4f40-b39f-4eaaaa47395e.mp4

On 1680 x 1050 resolution with firefox (It works correctely):
https://user-images.githubusercontent.com/38732192/232625568-09f716ef-8a09-4c87-b9d5-ec675de780e6.mp4

### For Iphone
Brave browser has the same problem as desktop version
Safari works correctely
Chrome works correctely

### Samsung galaxy S20
Brave browser same problem as desktop
Samsung internet works correctely
Chrome works correctely

**Comment by LFGaming** [comment]
Still a problem after the site update, but now it's called `partners` under resources.

**Comment by jefft0** [comment]
Hi @LFGaming . I think this behavior may have changed with the new website layout. Can you please confirm and update the issue?

**Comment by LFGaming** [comment]
> Hi @LFGaming . I think this behavior may have changed with the new website layout. Can you please confirm and update the issue?

Hi, yes it is still an issue on brave, I don't seem to be able to replicate the issue on firefox anymore.

**Comment by jefft0** [comment]
Hi @LFGaming . May I ask again if you can confirm that this is still an issue on Brave.

**Comment by LFGaming** [comment]
Hi @jefft0. There is no button to specific `Projects we love` anymore, so this is fixed
