### ISSUE TITLE
Missing images in updated web site

### ISSUE THREAD

**Issue by jefft0** [berty/www.berty.tech#391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Browser

Chrome

### Browser version

115

### OS

macOS

### OS version

Ventura

### Steps to reproduce

Navigate to:
https://berty.tech/wesh
https://berty.tech/messenger

### Current behavior

Missing images

### Expected behavior

Images should be present

### Other

As @LFGaming mentioned in the pull request https://github.com/berty/www.berty.tech/pull/385#issuecomment-1634275448 , some images are missing. The pull request was merged, so creating this issue to track this bug.

**Comment by LFGaming** [comment]
Building the site localy I have pitures at the pages, I'm not sure why then it does not show up on the live page, but maybe this helps?

**Comment by LFGaming** [comment]
Pull request #394 seems to have fixed it
