### ISSUE TITLE
Comment section is not working anymore

### ISSUE THREAD

**Issue by LFGaming** [berty/www.berty.tech#406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Browser

Brave

### Browser version

120.0.6099.199

### OS

Windows

### OS version

windows 11

### Steps to reproduce

Go to a blog post or newsletter scroll all the way down and you'll see the comment section block with an error in it.
This happens for me on all browsers (firefox, brave, chrome, edge, tor).

### Current behavior

It gives an error

### Expected behavior

It should either be gone or work in my opinion?

**Comment by jefft0** [comment]
Thanks @LFGaming . I see the same bug. We'll review this at our next QA meeting.

**Comment by jefft0** [comment]
Will look at removing the Comments from the template.

**Comment by costinberty** [comment]
@iuricmp could you please help with fixing this? I have a feeling it will be easy:
 - on any blogpost from our site (like this one [https://berty.tech/blog/ipfs-camp/] ) there is an error image/message in the Comments section. Depending on which solution is faster I suggest that:
 - either you fix the problem (if it's easy to fix) or
 - deactivate/remove the Comments section.

**Comment by jefft0** [comment]
Fixed by PR #409 .
