### ISSUE TITLE
Author Icon for Newsletters

### ISSUE THREAD

**Issue by LFGaming** [berty/www.berty.tech#410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Browser

Any browser

### Feature request

At the bottom of the newsletters there is a little icon with a name who wrote it:
![image](https://github.com/berty/www.berty.tech/assets/38732192/fadb7035-fe21-4035-b7da-e4aa5b6d9889)

@costinberty encouraged me to ask if i could have my own little thing for the newsletters I write :)

I tried to see how it worked and god something like this:
![image](https://github.com/berty/www.berty.tech/assets/38732192/c8f0bad9-b53b-4c8b-81a0-9a81cf1f5776)

What to put there exactly i do not know yet, but I thought id ask :)

### Context

See upper block

**Comment by jefft0** [comment]
@iuricmp , what should be changed in a PR to update this image?

**Comment by iuricmp** [comment]
hey @LFGaming 

Could you try this:

1. add your name in `data/authors.yml`
2. add an author in `content/newsletter/news-72/index.md`
```md
author: luke
title: "Berty News #72"
date: 2024-01-08
aliases: ["/newsletter/weekly-72"]
   ```
   
 3. test it locally: `make dev`

**Comment by jefft0** [comment]
Hi @LFGaming . Did the comment by @iuricmp answer your question?

**Comment by LFGaming** [comment]
Hi @jefft0 ,
It did, I'll make a pr in a bit :)

**Comment by iuricmp** [comment]
This issue was resolved in https://github.com/berty/www.berty.tech/pull/413
