### ISSUE TITLE
IPFS illustrations on Homepage

### ISSUE THREAD

**Issue by pierreboc** [berty/www.berty.tech#61]
Hi @cdeleeuwe,

Currently on the home page of the site at "Built for
the distributed web" there is an illustration that needs to be changed. Our graphic designer has been working on it. (see below the illustration). 

She also worked on an animated version. We're afraid that the loading time of the page will be too long. Can you give us your advice? 

Can you integrate his changes? The output files are either in GIF, MP4, H264, and JSON. 

If so, I will ask her the correct output version. 

Many thanks :) 

![image](https://user-images.githubusercontent.com/31745588/81820029-5b3e4d80-9530-11ea-89a4-3793999cefe5.png)

Animated version: https://trello-attachments.s3.amazonaws.com/5e5fa5e4549cce7e3d595cc3/5e5fae6cc887ee21c5d0d5d7/014b8e1d033b4a39872e224a25a1727b/2020-03-09-Berty-illu-IPFS-homepage-site-anim-Exemple-implantation.mp4

**Comment by cdeleeuwe** [comment]
@pierreboc not entirely sure which option is best. Can you share the JSON and MP4 files? And pls let me know which software is exporting it to JSON?

**Comment by pierreboc** [comment]
@cdeleeuwe Alright, I will ask her. She will export from After Effect.
